# Generated by Django 5.1.6 on 2025-02-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='contratista',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
