# Generated by Django 5.1.6 on 2025-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0003_niveleducativo_profesion_contratista_nivel_educativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
